### ISSUE TITLE
SPM Issues

### ISSUE THREAD

**Issue by JulesMoorhouse** [dkasaj/SwiftTipJar-SwiftUI-Example#1]
Hi,

I've been trying to add the SPM to my project and had issues.
https://github.com/dkasaj/SwiftTipJar.git

So I tried the example SwiftUI project
https://github.com/dkasaj/SwiftTipJar-SwiftUI-Example

However, it has the same issues..
```
Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2
```

Also when I added the SPM to my project, the readme didn't show in the SPM dialog, I guess this is the same problem.

Please advise.

Thanks,

Jules.

**Comment by dkasaj** [comment]
Hi Jules,
I'll see what I can do about this. For now, you might be able to get past this by either:

- going into Project Navigator, right clicking the package name and "Update package", or
- clicking File > Packages > Reset Package Caches

**Comment by JulesMoorhouse** [comment]
Thanks, however that doesn’t seem to work.

**Comment by dkasaj** [comment]
The last thing I can suggest to try to get this resolved quickly is https://stackoverflow.com/q/67185817

**Comment by JulesMoorhouse** [comment]
All older commits have the same issues.

Thanks for your prompt response 👍

**Comment by dkasaj** [comment]
Yeah I'm sorry you carved some time to try this out and are running into these errors.
You can get that SwiftUI example code working quickly if you copy paste the class file to its project
The class file is https://github.com/dkasaj/SwiftTipJar/blob/main/Sources/SwiftTipJar/SwiftTipJar.swift

**Comment by JulesMoorhouse** [comment]
Ah, looks like Xcode 13.3.1 works.
I was avoiding it for another issue.
🤔
